all:
	R CMD build ~/github/BioShiny/dataTable
	R CMD build ~/github/BioShiny/HeatmapWidget
	R CMD build ~/github/BioShiny/msgBox
	R CMD build ~/github/BioShiny/GOEnrichmentWidget
	R CMD build ~/github/igvShiny
	R CMD build ~/github/BioShiny/igvWidget
	R CMD build ~/github/BioShiny/GenomeTracksWidget

